version: '3.7'
services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one
    deploy:
      resources:
        limits:
          memory: 512m
    restart: unless-stopped
    networks:
      - parkingology
    ports:
      - '16686:16686'
      - '14268'
      - '14250'
  ocel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector:0.29.0
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - parkingology
    volumes:
      - type: bind
        source: /home/opc/jenkins_data/otel
        target: /etc
        read_only: false
    command: [ "--config=/etc/collector-gateway.yml" ]
    ports:
      - '1888:1888'   # pprof extension
      - '13133:13133' # health_check extension
      - '4317:4317'        # OTLP gRPC receiver
      - '4318:4318'        # OTLP HTTP receiver
      - '55670:55679' # zpages extension
    depends_on:
      - jaeger
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.16.3
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    container_name: kibana
    image: kibana:7.16.3
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - '9999:5601'
  logstash:
    container_name: logstash
    image: logstash:7.16.3
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - '5002:5000'
      - '9600:9600'
    volumes:
      - type: bind
        source: /home/opc/jenkins_data
        target: /usr/share/logstash/pipeline
        read_only: true
networks:
  parkingology:
    name: parking-network
